### ISSUE TITLE
Status is not correct

### ISSUE THREAD

**Issue by beathorst** [totten/git-scan#13]
The Status count one repo more than exist. In this example it is 4 repos not 5

me@localhost:~/drupal-demo$ git scan st
[[ Finding repositories ]]
[[ Checking statuses ]]
 5/5 [============================] 100%
[[ Results ]]

**Comment by totten** [comment]
The progress bar includes steps for (a) scanning the directory tree to locate the repos and (b) scanning each repo's status. That makes n+1 scanning steps.

The statuses should be reported in a table below `[[ Results ]]` -- eg

```
$ git scan st
[[ Finding repositories ]]
[[ Checking statuses ]]
 2/2 [============================] 100%
[[ Results ]]

+--------+----------+--------------------+---------------+
| Status | Path     | Local Branch / Tag | Remote Branch |
+--------+----------+--------------------+---------------+
|    N   | git-scan | master             | origin/master |
+--------+----------+--------------------+---------------+
[N] New files have not been committed
```

If it's not showing up at all... then there should be a message like

```
NOTE: Omitted information about $hiddenCount boring repo(s). To display all, use --status=all
```

If you don't see either of those, then I wonder if there's some kind PHP WSOD going on?

**Comment by beathorst** [comment]
OK for me it would be nice to have a count only for the repos.
we use ist for typo3 extention folder. there are sometimes 50 and more repos inside.
