### ISSUE TITLE
allow for arbitrary git commonads

### ISSUE THREAD

**Issue by splitbrain** [totten/git-scan#3]
Currently only status and update are possible with git-scan. It would be helpful to be able to run just any git command. Eg:

```
$ git scan fetch
```

The foreach command seems not to do that:
```
$ git scan foreach fetch
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'File not found: /var/www/dokuwiki/fetch' in phar:///var/www/git-scan.phar/src/GitScan/Util/Filesystem.php:78
```

**Comment by totten** [comment]
`foreach` should work with any shell command, including git subcommands, as in one of these examples:

```bash
git scan foreach -c 'git fetch origin'
git scan foreach -c 'pwd; git fetch origin'
git scan foreach -c 'git fetch -a'
```

It might be nice to have more shorthand/aliases (e.g. `git scan fetch`), but it's probably useful to think those through useful inputs+outputs on a case-by-case basis.

Tangential: I'd prefer a notation using `--` (e.g. `git scan foreach -- git fetch -a`), but the command parser in Symfony Console doesn't seem to support that, so one uses `-c` instead.

Tangential: I've also pushed through a new command, `ls`, which can be used for more advanced scripting, e.g.

```bash
git scan ls | while read path ; do ... done
```
